/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

public class App {
    public String getGreeting() {
        return "Hello arg00.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println("App says hello");
    }
}
